### ISSUE TITLE
Redstone wire doesn't get destroyed after bellow block gets destroyed

### ISSUE THREAD

**Issue by Gabriel8579** [GameModsBR/PowerNukkit#117] opened 2020-01-26 01:18 UTC
Look, this situation is correct:

![image](https://user-images.githubusercontent.com/31969146/73129357-68a2ec80-3fc0-11ea-8b2b-d1c72a68983a.png)

After destroying grass block:

![image](https://user-images.githubusercontent.com/31969146/73129359-75274500-3fc0-11ea-8563-207510522dc5.png)

But now, when the redstone wire is in a corner:

![image](https://user-images.githubusercontent.com/31969146/73129363-99832180-3fc0-11ea-994b-6e1281a502d8.png)

**Comment by joserobjr** [comment] 2020-01-26 17:44
I had reproduced this once but I'm unable to reproduce anymore, is it still happening?

Please if it does happens, show the coordinate with `/gamerule showCoordinates true`, I suspect it may be related to negative values.

https://youtu.be/3TtumYqf_AU

**Comment by Gabriel8579** [comment] 2020-01-26 21:21
Not happening anymore.

**Comment by joserobjr** [comment] 2020-01-27 01:13
Thank you, so I'm going to close it, we can reopen if it happens again.

**Closed by joserobjr** 2020-01-27 01:13 UTC
Labels: Status: Awaiting Response, Type: bug
