### ISSUE TITLE
I moved Nukkit 1.0 to PowerNukkit but I have many Raknet errors

### ISSUE THREAD

**Issue by good777LUCKY** [GameModsBR/PowerNukkit#312] opened 2020-06-30 12:11 UTC
# 🤷‍♀️ I have a question

I have many Raknet errors. What is these errors? Is this because of pluigns or worlds?

### 📸 Screenshots / Videos

```
2020-06-30 20:53:23.897 [Network Listener - #2] ERROR - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:107)
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:757)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.level.Level.sendBlocks(Level.java:1053)
	cn.nukkit.Player.handleDataPacket(Player.java:3229)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
2020-06-30 20:53:23.896 [Network Listener - #6] ERROR - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:107)
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:757)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.directDataPacket(Player.java:1100)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:742)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:177)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.entity.Entity.sendData(Entity.java:1162)
	cn.nukkit.entity.Entity.setDataProperty(Entity.java:2448)
	cn.nukkit.entity.Entity.setDataProperty(Entity.java:2441)
	cn.nukkit.entity.EntityLiving.setAirTicks(EntityLiving.java:393)
	cn.nukkit.entity.EntityLiving.entityBaseTick(EntityLiving.java:252)
	nukkitcoders.mobplugin.entities.BaseEntity.entityBaseTick(BaseEntity.java:148)
	nukkitcoders.mobplugin.entities.animal.SwimmingAnimal.entityBaseTick(SwimmingAnimal.java:31)
	nukkitcoders.mobplugin.entities.animal.SwimmingAnimal.onUpdate(SwimmingAnimal.java:53)
	cn.nukkit.level.Level.doTick(Level.java:862)
	cn.nukkit.Server.checkTickUpdates(Server.java:1107)
	cn.nukkit.Server.tick(Server.java:1189)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
2020-06-30 20:53:23.897 [Network Listener - #14] ERROR - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:107)
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:757)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.level.Level.setBlock(Level.java:1875)
	cn.nukkit.level.Level.setBlock(Level.java:1847)
	cn.nukkit.level.Level.setBlock(Level.java:1843)
	cn.nukkit.block.BlockBambooSapling.place(BlockBambooSapling.java:81)
	cn.nukkit.block.BlockBamboo.place(BlockBamboo.java:106)
	cn.nukkit.level.Level.useItemOn(Level.java:2347)
	cn.nukkit.level.Level.useItemOn(Level.java:2196)
	cn.nukkit.Player.handleDataPacket(Player.java:3210)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
2020-06-30 20:53:23.911 [Network Listener - #2] ERROR - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:107)
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:757)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.level.Level.sendBlocks(Level.java:1054)
	cn.nukkit.Player.handleDataPacket(Player.java:3229)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
2020-06-30 20:53:23.912 [Network Listener - #1] ERROR - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:702)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.Player.handleDataPacket(Player.java:3230)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:106)
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:757)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.Player.handleDataPacket(Player.java:3230)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#3:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:610)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:183)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.Player.handleDataPacket(Player.java:3230)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeByte(AdvancedLeakAwareByteBuf.java:544)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:182)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.Player.handleDataPacket(Player.java:3230)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:181)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Server.batchPackets(Server.java:676)
	cn.nukkit.level.Level.sendBlocks(Level.java:1111)
	cn.nukkit.level.Level.sendBlocks(Level.java:1063)
	cn.nukkit.Player.handleDataPacket(Player.java:3230)
	java.util.ArrayList.forEach(ArrayList.java:1257)
	cn.nukkit.network.Network.processPackets(Network.java:294)
	cn.nukkit.network.Network.processBatch(Network.java:279)
	cn.nukkit.Player.handleDataPacket(Player.java:2155)
	cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:77)
	cn.nukkit.network.Network.processInterfaces(Network.java:179)
	cn.nukkit.Server.tick(Server.java:1178)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
2020-06-30 20:53:23.912 [Network Listener - #5] ERROR - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:702)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readSlice(AdvancedLeakAwareByteBuf.java:118)
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:748)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#3:
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:744)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:610)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:183)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#5:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeByte(AdvancedLeakAwareByteBuf.java:544)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:182)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:181)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
: 2 leak records were discarded because they were duplicates
: 18 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.
2020-06-30 20:53:23.913 [Network Listener - #2] ERROR - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:702)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readSlice(AdvancedLeakAwareByteBuf.java:118)
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:748)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#3:
	com.nukkitx.network.raknet.RakNetSession.createEncapsulated(RakNetSession.java:744)
	com.nukkitx.network.raknet.RakNetSession.send(RakNetSession.java:682)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:186)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:610)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:183)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
#5:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeByte(AdvancedLeakAwareByteBuf.java:544)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:182)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	cn.nukkit.network.RakNetInterface.putPacket(RakNetInterface.java:181)
	cn.nukkit.Player.dataPacket(Player.java:1071)
	cn.nukkit.Server.broadcastPacketsCallback(Server.java:748)
	cn.nukkit.Server.batchPackets(Server.java:718)
	cn.nukkit.Player.checkNetwork(Player.java:1897)
	cn.nukkit.Server.tick(Server.java:1192)
	cn.nukkit.Server.tickProcessor(Server.java:961)
	cn.nukkit.Server.start(Server.java:929)
	cn.nukkit.Server.<init>(Server.java:587)
	cn.nukkit.Nukkit.main(Nukkit.java:119)
: 1 leak records were discarded because they were duplicates
: 15 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.
```

### 📋 Debug information

* PowerNukkit version: PN-115 (a80287f)
* Debug link:

**Comment by joserobjr** [comment] 2020-06-30 13:50
I'm going to investigate for possible leaks using the given stack traces. I hadn't seen these warnings yet.

Please, send us the link generated by `/debugpaste` it will create a link with recent log, some configuration file, plugin list and some other useful information to trace the issue. The link is temporary and expires after some days (30 days, I think, maybe more).

**Comment by joserobjr** [comment] 2020-06-30 16:18
Can you check if this build solves your problem?
https://github.com/GameModsBR/PowerNukkit/actions/runs/152994253

Direct download link: https://github.com/GameModsBR/PowerNukkit/suites/859522149/artifacts/9883448

**Comment by joserobjr** [comment] 2020-06-30 16:37
Since the commits are coming quickly, you might want to get the latest version from this link:
https://github.com/GameModsBR/PowerNukkit/actions

**Comment by good777LUCKY** [comment] 2020-07-01 03:26
Fixed but I think MobPlugin causing some freeze

**Comment by good777LUCKY** [comment] 2020-07-01 03:50
![Screenshot](https://user-images.githubusercontent.com/43497313/86201060-6a896100-bb99-11ea-82dc-ed699b376faa.jpg)
Do you know this error? I can't start server.

**Comment by good777LUCKY** [comment] 2020-07-01 04:28
Also, I was using Nukkit 1.0 and wode Chemistry plugin, I moved to powernukkit and I open a chest that have chemistry things, client will crash even I disable chemistry plugin.
(Chemistry Plugin: https://github.com/wode490390/ChemistryGameplay)

**Comment by joserobjr** [comment] 2020-07-01 04:37
@good777LUCKY  I created a new issue for that: https://github.com/GameModsBR/PowerNukkit/issues/316

**Comment by good777LUCKY** [comment] 2020-07-01 05:25
Thank you

**Comment by joserobjr** [comment] 2020-07-01 05:49
I'm closing as fixed because I believe that the issue is not going to happen anymore, however if it occurs, feel free to reopen the issue.

**Closed by joserobjr** 2020-07-01 05:49 UTC
Labels: Type: bug
